CREATE TABLE [dbo].[RawData_01142020] (
    [S#O#]               NVARCHAR (255) NULL,
    [Active Status]      NVARCHAR (255) NULL,
    [Vendor]             NVARCHAR (255) NULL,
    [Bill from Street 1] NVARCHAR (255) NULL,
    [Bill from Street 2] NVARCHAR (255) NULL,
    [Bill from City]     NVARCHAR (255) NULL,
    [Bill from State]    NVARCHAR (255) NULL,
    [Bill from Zip]      NVARCHAR (255) NULL,
    [Bill from Country]  NVARCHAR (255) NULL,
    [Account No#]        NVARCHAR (255) NULL,
    [Bill from 1]        NVARCHAR (255) NULL,
    [Bill from 2]        NVARCHAR (255) NULL,
    [Bill from 3]        NVARCHAR (255) NULL,
    [Bill from 4]        NVARCHAR (255) NULL,
    [Bill from 5]        NVARCHAR (255) NULL,
    [Bill from]          NVARCHAR (255) NULL,
    [Main Email]         NVARCHAR (255) NULL,
    [Primary Contact]    NVARCHAR (255) NULL,
    [Company]            NVARCHAR (255) NULL,
    [First Name]         NVARCHAR (255) NULL,
    [Last Name]          NVARCHAR (255) NULL,
    [Main Phone]         NVARCHAR (255) NULL,
    [Work Phone]         NVARCHAR (255) NULL,
    [Fax]                NVARCHAR (255) NULL,
    [Balance Total]      FLOAT (53)     NULL,
    [Vendor Type]        NVARCHAR (255) NULL,
    [Tax ID]             NVARCHAR (255) NULL,
    [NS Party ID]        NVARCHAR (255) NULL,
    [F29]                NVARCHAR (255) NULL
);

