CREATE TABLE [dbo].[Checks] (
    [SO_Name]              VARCHAR (5)     NULL,
    [ID]                   NVARCHAR (255)  NULL,
    [ReferenceNumber]      NVARCHAR (42)   NULL,
    [TxnNumber]            INT             NULL,
    [Account]              NVARCHAR (510)  NULL,
    [AccountId]            NVARCHAR (510)  NULL,
    [Payee]                NVARCHAR (510)  NULL,
    [PayeeId]              NVARCHAR (510)  NULL,
    [Date]                 DATE            NULL,
    [Amount]               DECIMAL (31, 6) NULL,
    [Memo]                 NVARCHAR (MAX)  NULL,
    [Address]              NVARCHAR (MAX)  NULL,
    [Line1]                NVARCHAR (1000) NULL,
    [Line2]                NVARCHAR (1000) NULL,
    [Line3]                NVARCHAR (1000) NULL,
    [Line4]                NVARCHAR (1000) NULL,
    [Line5]                NVARCHAR (82)   NULL,
    [City]                 NVARCHAR (510)  NULL,
    [State]                NVARCHAR (510)  NULL,
    [PostalCode]           NVARCHAR (60)   NULL,
    [Country]              NVARCHAR (510)  NULL,
    [Note]                 NVARCHAR (82)   NULL,
    [ItemCount]            INT             NULL,
    [ItemAggregate]        NVARCHAR (MAX)  NULL,
    [ExpenseItemCount]     INT             NULL,
    [ExpenseItemAggregate] NVARCHAR (MAX)  NULL,
    [IsToBePrinted]        BIT             NULL,
    [IsTaxIncluded]        BIT             NULL,
    [CurrencyName]         NVARCHAR (128)  NULL,
    [CurrencyId]           NVARCHAR (510)  NULL,
    [ExchangeRate]         FLOAT (53)      NULL,
    [CustomFields]         NVARCHAR (MAX)  NULL,
    [TimeModified]         DATETIME        NULL,
    [TimeCreated]          DATETIME        NULL
);

