CREATE TABLE [dbo].[Check_LineItems] (
    [ID]                            NVARCHAR (255)  NOT NULL,
    [SO_Name]                       VARCHAR (5)     NULL,
    [CheckId]                       NVARCHAR (510)  NULL,
    [ReferenceNumber]               NVARCHAR (42)   NULL,
    [TxnNumber]                     INT             NULL,
    [Account]                       NVARCHAR (510)  NULL,
    [AccountId]                     NVARCHAR (510)  NULL,
    [Payee]                         NVARCHAR (510)  NULL,
    [PayeeId]                       NVARCHAR (510)  NULL,
    [Date]                          DATE            NULL,
    [Amount]                        DECIMAL (31, 6) NULL,
    [Memo]                          NVARCHAR (MAX)  NULL,
    [Address]                       NVARCHAR (MAX)  NULL,
    [Line1]                         NVARCHAR (1000) NULL,
    [Line2]                         NVARCHAR (1000) NULL,
    [Line3]                         NVARCHAR (1000) NULL,
    [Line4]                         NVARCHAR (1000) NULL,
    [Line5]                         NVARCHAR (82)   NULL,
    [City]                          NVARCHAR (510)  NULL,
    [State]                         NVARCHAR (510)  NULL,
    [PostalCode]                    NVARCHAR (60)   NULL,
    [Country]                       NVARCHAR (510)  NULL,
    [Note]                          NVARCHAR (82)   NULL,
    [CustomFields]                  NVARCHAR (MAX)  NULL,
    [ItemLineId]                    NVARCHAR (510)  NULL,
    [ItemLineNumber]                NVARCHAR (510)  NULL,
    [ItemName]                      NVARCHAR (510)  NULL,
    [ItemId]                        NVARCHAR (510)  NULL,
    [ItemGroup]                     NVARCHAR (200)  NULL,
    [ItemGroupId]                   NVARCHAR (510)  NULL,
    [ItemDescription]               NVARCHAR (MAX)  NULL,
    [ItemQuantity]                  FLOAT (53)      NULL,
    [ItemUnitOfMeasure]             NVARCHAR (62)   NULL,
    [ItemCost]                      FLOAT (53)      NULL,
    [ItemAmount]                    DECIMAL (31, 6) NULL,
    [ItemBillableStatus]            NVARCHAR (26)   NULL,
    [ItemCustomer]                  NVARCHAR (510)  NULL,
    [ItemCustomerId]                NVARCHAR (510)  NULL,
    [ItemClass]                     NVARCHAR (510)  NULL,
    [ItemClassId]                   NVARCHAR (510)  NULL,
    [ItemInventorySiteId]           NVARCHAR (62)   NULL,
    [ItemInventorySiteName]         NVARCHAR (510)  NULL,
    [ItemInventorySiteLocationId]   NVARCHAR (62)   NULL,
    [ItemInventorySiteLocationName] NVARCHAR (510)  NULL,
    [ItemTaxCode]                   NVARCHAR (6)    NULL,
    [ItemTaxCodeId]                 NVARCHAR (510)  NULL,
    [ItemCustomFields]              NVARCHAR (MAX)  NULL,
    [IsToBePrinted]                 BIT             NULL,
    [IsTaxIncluded]                 BIT             NULL,
    [CurrencyName]                  NVARCHAR (128)  NULL,
    [CurrencyId]                    NVARCHAR (510)  NULL,
    [ExchangeRate]                  FLOAT (53)      NULL,
    [TimeModified]                  DATETIME        NULL,
    [TimeCreated]                   DATETIME        NULL,
    CONSTRAINT [PK_Check_LineItems] PRIMARY KEY CLUSTERED ([ID] ASC)
);

