CREATE TABLE [dbo].[DepositLineItems] (
    [ID]                 NVARCHAR (255)  NULL,
    [DepositId]          NVARCHAR (510)  NULL,
    [TxnNumber]          INT             NULL,
    [Date]               DATE            NULL,
    [CashBackAccount]    NVARCHAR (510)  NULL,
    [CashBackAccountId]  NVARCHAR (510)  NULL,
    [CashBackAmount]     DECIMAL (31, 6) NULL,
    [CashBackId]         NVARCHAR (510)  NULL,
    [CashBackMemo]       NVARCHAR (MAX)  NULL,
    [DepositToAccount]   NVARCHAR (510)  NULL,
    [DepositToAccountId] NVARCHAR (510)  NULL,
    [Memo]               NVARCHAR (MAX)  NULL,
    [TotalDeposit]       FLOAT (53)      NULL,
    [CustomFields]       NVARCHAR (MAX)  NULL,
    [ItemLineId]         NVARCHAR (510)  NULL,
    [ItemAccount]        NVARCHAR (510)  NULL,
    [ItemAccountId]      NVARCHAR (510)  NULL,
    [ItemAmount]         DECIMAL (31, 6) NULL,
    [ItemCheckNumber]    NVARCHAR (22)   NULL,
    [ItemClass]          NVARCHAR (510)  NULL,
    [ItemClassId]        NVARCHAR (510)  NULL,
    [ItemEntityName]     NVARCHAR (418)  NULL,
    [ItemEntityId]       NVARCHAR (510)  NULL,
    [ItemMemo]           NVARCHAR (MAX)  NULL,
    [ItemPaymentMethod]  NVARCHAR (62)   NULL,
    [ItemPaymentId]      NVARCHAR (510)  NULL,
    [ItemPaymentLineId]  NVARCHAR (510)  NULL,
    [ItemRefId]          NVARCHAR (510)  NULL,
    [ItemTxnType]        NVARCHAR (200)  NULL,
    [CurrencyName]       NVARCHAR (128)  NULL,
    [CurrencyId]         NVARCHAR (510)  NULL,
    [ExchangeRate]       FLOAT (53)      NULL,
    [TimeModified]       DATETIME        NULL,
    [TimeCreated]        DATETIME        NULL,
    [Payee]              NVARCHAR (510)  NULL,
    [PayeeId]            NVARCHAR (510)  NULL
);

