CREATE TABLE [dbo].[JournalEntryLine] (
    [ID]                       NVARCHAR (255)  NULL,
    [JournalEntryID]           NVARCHAR (510)  NULL,
    [ReferenceNumber]          NVARCHAR (42)   NULL,
    [TxnNumber]                INT             NULL,
    [Date]                     DATE            NULL,
    [CreditLineCount]          INT             NULL,
    [DebitLineCount]           INT             NULL,
    [LineId]                   NVARCHAR (510)  NULL,
    [LineType]                 NVARCHAR (200)  NULL,
    [LineAccount]              NVARCHAR (510)  NULL,
    [LineAccountId]            NVARCHAR (510)  NULL,
    [LineAmount]               DECIMAL (31, 6) NULL,
    [LineEntityName]           NVARCHAR (MAX)  NULL,
    [LineEntityId]             NVARCHAR (510)  NULL,
    [LineMemo]                 NVARCHAR (MAX)  NULL,
    [LineClass]                NVARCHAR (510)  NULL,
    [LineClassId]              NVARCHAR (510)  NULL,
    [LineStatus]               NVARCHAR (26)   NULL,
    [LineTaxItem]              NVARCHAR (200)  NULL,
    [LineTaxItemId]            NVARCHAR (510)  NULL,
    [CurrencyName]             NVARCHAR (128)  NULL,
    [CurrencyId]               NVARCHAR (510)  NULL,
    [ExchangeRate]             FLOAT (53)      NULL,
    [IsHomeCurrencyAdjustment] BIT             NULL,
    [EditSequence]             NVARCHAR (32)   NULL,
    [TimeModified]             DATETIME        NULL,
    [TimeCreated]              DATETIME        NULL
);

