CREATE TABLE [dbo].[SalesRecepts] (
    [ID]                 NVARCHAR (255)  NULL,
    [ReferenceNumber]    NVARCHAR (42)   NULL,
    [TxnNumber]          INT             NULL,
    [CustomerName]       NVARCHAR (510)  NULL,
    [CustomerId]         NVARCHAR (510)  NULL,
    [Date]               DATE            NULL,
    [ShipMethod]         NVARCHAR (510)  NULL,
    [ShipMethodId]       NVARCHAR (510)  NULL,
    [ShipDate]           DATE            NULL,
    [Memo]               NVARCHAR (MAX)  NULL,
    [Class]              NVARCHAR (510)  NULL,
    [ClassId]            NVARCHAR (510)  NULL,
    [DueDate]            DATE            NULL,
    [TotalAmount]        DECIMAL (31, 6) NULL,
    [Message]            NVARCHAR (202)  NULL,
    [MessageId]          NVARCHAR (510)  NULL,
    [SalesRep]           NVARCHAR (10)   NULL,
    [SalesRepId]         NVARCHAR (510)  NULL,
    [Template]           NVARCHAR (200)  NULL,
    [TemplateId]         NVARCHAR (510)  NULL,
    [ExchangeRate]       FLOAT (53)      NULL,
    [FOB]                NVARCHAR (26)   NULL,
    [BillingAddress]     NVARCHAR (MAX)  NULL,
    [BillingLine1]       NVARCHAR (1000) NULL,
    [BillingLine2]       NVARCHAR (1000) NULL,
    [BillingLine3]       NVARCHAR (1000) NULL,
    [BillingLine4]       NVARCHAR (1000) NULL,
    [BillingLine5]       NVARCHAR (82)   NULL,
    [BillingCity]        NVARCHAR (510)  NULL,
    [BillingState]       NVARCHAR (510)  NULL,
    [BillingPostalCode]  NVARCHAR (60)   NULL,
    [BillingCountry]     NVARCHAR (510)  NULL,
    [BillingNote]        NVARCHAR (82)   NULL,
    [ShippingAddress]    NVARCHAR (MAX)  NULL,
    [ShippingLine1]      NVARCHAR (1000) NULL,
    [ShippingLine2]      NVARCHAR (1000) NULL,
    [ShippingLine3]      NVARCHAR (1000) NULL,
    [ShippingLine4]      NVARCHAR (1000) NULL,
    [ShippingLine5]      NVARCHAR (82)   NULL,
    [ShippingCity]       NVARCHAR (510)  NULL,
    [ShippingState]      NVARCHAR (510)  NULL,
    [ShippingPostalCode] NVARCHAR (60)   NULL,
    [ShippingCountry]    NVARCHAR (510)  NULL,
    [ShippingNote]       NVARCHAR (82)   NULL,
    [Subtotal]           DECIMAL (31, 6) NULL,
    [Tax]                FLOAT (53)      NULL,
    [TaxItem]            NVARCHAR (200)  NULL,
    [TaxItemId]          NVARCHAR (510)  NULL,
    [TaxPercent]         FLOAT (53)      NULL,
    [IsPending]          BIT             NULL,
    [IsToBePrinted]      BIT             NULL,
    [IsTaxIncluded]      BIT             NULL,
    [IsToBeEmailed]      BIT             NULL,
    [ItemCount]          INT             NULL,
    [ItemAggregate]      NVARCHAR (MAX)  NULL,
    [CheckNumber]        NVARCHAR (50)   NULL,
    [PaymentMethod]      NVARCHAR (200)  NULL,
    [PaymentMethodId]    NVARCHAR (510)  NULL,
    [DepositAccount]     NVARCHAR (510)  NULL,
    [DepositAccountId]   NVARCHAR (510)  NULL,
    [CustomerTaxCode]    NVARCHAR (6)    NULL,
    [CustomerTaxCodeId]  NVARCHAR (510)  NULL,
    [CustomFields]       NVARCHAR (MAX)  NULL,
    [EditSequence]       NVARCHAR (32)   NULL,
    [TimeModified]       DATETIME        NULL,
    [TimeCreated]        DATETIME        NULL
);

