CREATE TABLE [dbo].[tblSalesReceipts_LineItems] (
    [ID]                         NVARCHAR (255)  NOT NULL,
    [SO_Name]                    VARCHAR (5)     NULL,
    [SalesReceiptId]             NVARCHAR (510)  NULL,
    [ReferenceNumber]            NVARCHAR (42)   NULL,
    [TxnNumber]                  INT             NULL,
    [CustomerName]               NVARCHAR (510)  NULL,
    [CustomerId]                 NVARCHAR (510)  NULL,
    [Date]                       DATE            NULL,
    [ShipMethod]                 NVARCHAR (510)  NULL,
    [ShipMethodId]               NVARCHAR (510)  NULL,
    [ShipDate]                   DATE            NULL,
    [Memo]                       NVARCHAR (MAX)  NULL,
    [Class]                      NVARCHAR (510)  NULL,
    [ClassId]                    NVARCHAR (510)  NULL,
    [DueDate]                    DATE            NULL,
    [TotalAmount]                DECIMAL (31, 6) NULL,
    [Message]                    NVARCHAR (202)  NULL,
    [MessageId]                  NVARCHAR (510)  NULL,
    [SalesRep]                   NVARCHAR (10)   NULL,
    [SalesRepId]                 NVARCHAR (510)  NULL,
    [Template]                   NVARCHAR (200)  NULL,
    [TemplateId]                 NVARCHAR (510)  NULL,
    [ExchangeRate]               FLOAT (53)      NULL,
    [FOB]                        NVARCHAR (26)   NULL,
    [BillingAddress]             NVARCHAR (MAX)  NULL,
    [BillingLine1]               NVARCHAR (1000) NULL,
    [BillingLine2]               NVARCHAR (1000) NULL,
    [BillingLine3]               NVARCHAR (1000) NULL,
    [BillingLine4]               NVARCHAR (1000) NULL,
    [BillingLine5]               NVARCHAR (82)   NULL,
    [BillingCity]                NVARCHAR (510)  NULL,
    [BillingState]               NVARCHAR (510)  NULL,
    [BillingPostalCode]          NVARCHAR (60)   NULL,
    [BillingCountry]             NVARCHAR (510)  NULL,
    [BillingNote]                NVARCHAR (82)   NULL,
    [ShippingAddress]            NVARCHAR (MAX)  NULL,
    [ShippingLine1]              NVARCHAR (1000) NULL,
    [ShippingLine2]              NVARCHAR (1000) NULL,
    [ShippingLine3]              NVARCHAR (1000) NULL,
    [ShippingLine4]              NVARCHAR (1000) NULL,
    [ShippingLine5]              NVARCHAR (82)   NULL,
    [ShippingCity]               NVARCHAR (510)  NULL,
    [ShippingState]              NVARCHAR (510)  NULL,
    [ShippingPostalCode]         NVARCHAR (60)   NULL,
    [ShippingCountry]            NVARCHAR (510)  NULL,
    [ShippingNote]               NVARCHAR (82)   NULL,
    [Subtotal]                   DECIMAL (31, 6) NULL,
    [Tax]                        FLOAT (53)      NULL,
    [TaxItem]                    NVARCHAR (200)  NULL,
    [TaxItemId]                  NVARCHAR (510)  NULL,
    [TaxPercent]                 FLOAT (53)      NULL,
    [IsPending]                  BIT             NULL,
    [IsToBePrinted]              BIT             NULL,
    [IsTaxIncluded]              BIT             NULL,
    [IsToBeEmailed]              BIT             NULL,
    [ItemLineId]                 NVARCHAR (510)  NULL,
    [ItemLineNumber]             NVARCHAR (510)  NULL,
    [ItemName]                   NVARCHAR (510)  NULL,
    [ItemId]                     NVARCHAR (510)  NULL,
    [ItemGroup]                  NVARCHAR (200)  NULL,
    [ItemGroupId]                NVARCHAR (510)  NULL,
    [ItemDescription]            NVARCHAR (MAX)  NULL,
    [ItemQuantity]               FLOAT (53)      NULL,
    [ItemUnitOfMeasure]          NVARCHAR (62)   NULL,
    [ItemRate]                   FLOAT (53)      NULL,
    [ItemRatePercent]            FLOAT (53)      NULL,
    [ItemTaxCode]                NVARCHAR (6)    NULL,
    [ItemTaxCodeId]              NVARCHAR (510)  NULL,
    [ItemAmount]                 DECIMAL (31, 6) NULL,
    [ItemInventorySiteName]      NVARCHAR (62)   NULL,
    [ItemInventorySiteId]        NVARCHAR (510)  NULL,
    [ItemSerialNumber]           NVARCHAR (MAX)  NULL,
    [ItemLotNumber]              NVARCHAR (80)   NULL,
    [ItemClass]                  NVARCHAR (510)  NULL,
    [ItemClassId]                NVARCHAR (510)  NULL,
    [ItemUOMSetFullName]         NVARCHAR (510)  NULL,
    [ItemUOMSetListID]           NVARCHAR (510)  NULL,
    [ItemIsGetPrintItemsInGroup] NVARCHAR (MAX)  NULL,
    [CheckNumber]                NVARCHAR (50)   NULL,
    [PaymentMethod]              NVARCHAR (200)  NULL,
    [PaymentMethodId]            NVARCHAR (510)  NULL,
    [DepositAccount]             NVARCHAR (510)  NULL,
    [DepositAccountId]           NVARCHAR (510)  NULL,
    [CustomerTaxCode]            NVARCHAR (6)    NULL,
    [CustomerTaxCodeId]          NVARCHAR (510)  NULL,
    [CustomFields]               NVARCHAR (MAX)  NULL,
    [EditSequence]               NVARCHAR (32)   NULL,
    [TimeModified]               DATETIME        NULL,
    [TimeCreated]                DATETIME        NULL,
    CONSTRAINT [PK_tblSalesReceipts_LineItems] PRIMARY KEY CLUSTERED ([ID] ASC)
);

