CREATE TABLE [dbo].[Vendor] (
    [ID]                  NVARCHAR (255)  NULL,
    [Name]                NVARCHAR (200)  NULL,
    [Salutation]          NVARCHAR (30)   NULL,
    [FirstName]           NVARCHAR (50)   NULL,
    [MiddleInitial]       NVARCHAR (50)   NULL,
    [LastName]            NVARCHAR (50)   NULL,
    [Company]             NVARCHAR (100)  NULL,
    [Contact]             NVARCHAR (MAX)  NULL,
    [AccountNumber]       NVARCHAR (198)  NULL,
    [Type]                NVARCHAR (MAX)  NULL,
    [TypeId]              NVARCHAR (510)  NULL,
    [CreditLimit]         FLOAT (53)      NULL,
    [TaxIdentity]         NVARCHAR (40)   NULL,
    [SalesTaxCountry]     NVARCHAR (200)  NULL,
    [AlternateContact]    NVARCHAR (82)   NULL,
    [Phone]               NVARCHAR (42)   NULL,
    [Fax]                 NVARCHAR (42)   NULL,
    [AlternatePhone]      NVARCHAR (42)   NULL,
    [Email]               NVARCHAR (MAX)  NULL,
    [Cc]                  NVARCHAR (MAX)  NULL,
    [Notes]               NVARCHAR (MAX)  NULL,
    [Address]             NVARCHAR (MAX)  NULL,
    [Line1]               NVARCHAR (1000) NULL,
    [Line2]               NVARCHAR (1000) NULL,
    [Line3]               NVARCHAR (1000) NULL,
    [Line4]               NVARCHAR (1000) NULL,
    [Line5]               NVARCHAR (82)   NULL,
    [City]                NVARCHAR (510)  NULL,
    [State]               NVARCHAR (510)  NULL,
    [PostalCode]          NVARCHAR (60)   NULL,
    [Country]             NVARCHAR (510)  NULL,
    [Note]                NVARCHAR (82)   NULL,
    [ShippingAddress]     NVARCHAR (MAX)  NULL,
    [ShippingLine1]       NVARCHAR (1000) NULL,
    [ShippingLine2]       NVARCHAR (1000) NULL,
    [ShippingLine3]       NVARCHAR (1000) NULL,
    [ShippingLine4]       NVARCHAR (1000) NULL,
    [ShippingLine5]       NVARCHAR (82)   NULL,
    [ShippingCity]        NVARCHAR (510)  NULL,
    [ShippingState]       NVARCHAR (510)  NULL,
    [ShippingPostalCode]  NVARCHAR (60)   NULL,
    [ShippingCountry]     NVARCHAR (510)  NULL,
    [ShippingNote]        NVARCHAR (82)   NULL,
    [Balance]             FLOAT (53)      NULL,
    [Terms]               NVARCHAR (200)  NULL,
    [TermsId]             NVARCHAR (510)  NULL,
    [EligibleFor1099]     BIT             NULL,
    [NameOnCheck]         NVARCHAR (220)  NULL,
    [CurrencyName]        NVARCHAR (128)  NULL,
    [CurrencyId]          NVARCHAR (510)  NULL,
    [IsActive]            BIT             NULL,
    [CustomFields]        NVARCHAR (MAX)  NULL,
    [EditSequence]        NVARCHAR (32)   NULL,
    [TimeModified]        DATETIME        NULL,
    [TimeCreated]         DATETIME        NULL,
    [PrefillAccountId1]   NVARCHAR (MAX)  NULL,
    [PrefillAccountName1] NVARCHAR (MAX)  NULL,
    [PrefillAccountId2]   NVARCHAR (MAX)  NULL,
    [PrefillAccountName2] NVARCHAR (MAX)  NULL,
    [PrefillAccountId3]   NVARCHAR (MAX)  NULL,
    [PrefillAccountName3] NVARCHAR (MAX)  NULL
);

